# Generated by Django 5.2.17 on 2026-08-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_character_archived_at_character_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterLocationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_state",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__gte", -90),
                            ("latitude__lte", 90),
                        ),
                        name="character_location_latitude_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__gte", -180),
                            ("longitude__lt", 180),
                        ),
                        name="character_location_longitude_range",
                    ),
                ],
            },
        ),
    ]
