# Generated by Django 5.2.17 on 2026-08-25

import django.db.models.deletion
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_character_location_state_l1"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("memo", models.CharField(blank=True, max_length=120)),
                (
                    "body",
                    models.TextField(
                        max_length=32768,
                        validators=[django.core.validators.MaxLengthValidator(32768)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_notes",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["character", "updated_at"],
                        name="char_note_character_time_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("body", ""), _negated=True),
                        name="character_note_body_not_empty",
                    ),
                ],
            },
        ),
    ]
