# Generated by Django 5.2.17 on 2026-08-21 15:02

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def ensure_case_insensitive_email_uniqueness(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    duplicates = list(
        User.objects.exclude(email='')
        .annotate(normalized=django.db.models.functions.text.Lower('email'))
        .values('normalized')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
        .values_list('normalized', flat=True)[:10]
    )
    if duplicates:
        raise RuntimeError(
            'Cannot add case-insensitive email uniqueness: resolve duplicate '
            f'addresses first ({", ".join(duplicates)}).'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_snapshot', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=256)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_failed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_required',
            field=models.BooleanField(default=False, help_text='Включается для публичной регистрации и поддерживаемой смены email. Старые аккаунты не помечаются подтверждёнными автоматически.', verbose_name='Требовать подтверждение email'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Email подтверждён'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.EmailField(blank=True, editable=False, max_length=254, verbose_name='Подтверждённый email'),
        ),
        migrations.RunPython(
            ensure_case_insensitive_email_uniqueness,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='accounts_user_email_ci_unique'),
        ),
        migrations.AddField(
            model_name='emailverificationchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailverificationchallenge',
            index=models.Index(fields=['user', 'created_at'], name='email_verify_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationchallenge',
            index=models.Index(fields=['expires_at'], name='email_verify_expires_idx'),
        ),
    ]
