# Generated by Django 5.2.17 on 2026-08-08 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('biome', models.CharField(choices=[('plains', 'Равнины'), ('forest', 'Лес'), ('desert', 'Пустыня'), ('mountains', 'Горы'), ('tundra', 'Тундра'), ('swamp', 'Болото'), ('coast', 'Побережье')], max_length=30)),
                ('base_temperature', models.FloatField(default=10)),
                ('seasonal_amplitude', models.FloatField(default=15)),
                ('humidity', models.FloatField(default=50)),
                ('elevation', models.FloatField(default=0)),
                ('weather_volatility', models.FloatField(default=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_minutes', models.BigIntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField(default=0)),
                ('precipitation', models.FloatField(default=0)),
                ('condition', models.CharField(choices=[('clear', 'Ясно'), ('cloudy', 'Облачно'), ('rain', 'Дождь'), ('storm', 'Гроза'), ('snow', 'Снег'), ('fog', 'Туман')], max_length=20)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_history', to='world.region')),
            ],
            options={
                'ordering': ['-world_minutes'],
            },
        ),
        migrations.CreateModel(
            name='WorldEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_at', models.BigIntegerField(help_text='Игровая минута запуска')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('triggered', 'Произошло'), ('cancelled', 'Отменено')], default='planned', max_length=20)),
                ('visible_to_players', models.BooleanField(default=False)),
                ('triggered_at', models.BigIntegerField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaigns.campaign')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='world.region')),
            ],
            options={
                'ordering': ['trigger_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('campaign', 'name'), name='unique_region_name_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='weatherstate',
            constraint=models.UniqueConstraint(fields=('region', 'world_minutes'), name='unique_weather_state_per_region_time'),
        ),
    ]
