# Generated by Django 5.2.17 on 2026-08-08 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='elevation_temperature_per_1000m',
            field=models.FloatField(default=-6.5, help_text='Настраиваемая поправка температуры на 1000 единиц высоты, °C.'),
        ),
        migrations.AddField(
            model_name='region',
            name='light_cycle_temperature_amplitude',
            field=models.FloatField(default=6, help_text='Настраиваемая сила влияния длинного светового цикла, °C.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='region',
            name='weather_persistence',
            field=models.FloatField(default=0.72, help_text='Инерция погоды: 0 — быстрая смена, 1 — максимальная устойчивость.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='region',
            name='weather_update_interval_minutes',
            field=models.PositiveIntegerField(default=360, help_text='Минимальный интервал между новыми состояниями погоды.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='region',
            name='ympha_temperature_influence',
            field=models.FloatField(default=3, help_text='Настраиваемое влияние видимой Ympha ночью, °C.'),
        ),
    ]
