# Generated by Django 5.2.17 on 2026-08-08 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_region_elevation_temperature_per_1000m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='map_latitude',
            field=models.FloatField(blank=True, help_text='Центр региона по широте на мировой карте.', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='region',
            name='map_longitude',
            field=models.FloatField(blank=True, help_text='Центр региона по долготе на мировой карте.', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='region',
            name='map_polygon',
            field=models.JSONField(blank=True, default=list, help_text='Контур региона как нормализованные точки карты [[x, y], ...].'),
        ),
    ]
