# Generated by Django 5.2.17 on 2026-08-09 01:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_star_motion_direction_and_more'),
        ('world', '0003_region_map_latitude_region_map_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='precipitation_bias',
            field=models.FloatField(default=0, help_text='Локальная поправка к вероятности осадков: отрицательная для сухих земель, положительная для влажных.', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='region',
            name='season_light_temperature_influence',
            field=models.FloatField(default=5, help_text='Сила влияния Светлого или Тёмного сезона на температуру, °C. Значение остаётся настройкой региона, пока канон не задаёт точную величину.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='region',
            name='humidity',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='region',
            name='seasonal_amplitude',
            field=models.FloatField(default=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='region',
            name='weather_volatility',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.CreateModel(
            name='WorldMapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_width', models.PositiveSmallIntegerField(default=180, editable=False)),
                ('grid_height', models.PositiveSmallIntegerField(default=90, editable=False)),
                ('biome_cells', models.JSONField(blank=True, default=dict, help_text='Разреженная сетка биомов: индекс ячейки -> код биома.')),
                ('elevation_cells', models.JSONField(blank=True, default=dict, help_text='Разреженная сетка высот: индекс ячейки -> высота.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='world_map_layer', to='campaigns.campaign')),
            ],
        ),
    ]
