# Generated by Django 5.2.17 on 2026-08-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_alter_atmosphericsnapshot_solver_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmosphericconfig',
            name='ocean_temperature_c',
            field=models.FloatField(blank=True, help_text='Fallback температуры океана только для пикселей без значения на карте средней температуры. Не заменяет динамическую SST.', null=True),
        ),
        migrations.AlterField(
            model_name='atmosphericsnapshot',
            name='format_version',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='atmosphericsnapshot',
            name='solver_version',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
