# Generated by Django 5.2 for Fardecosmia Phase C3.

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0011_alter_atmosphericconfig_ocean_temperature_c_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atmosphericconfig",
            name="oxygen_fraction",
            field=models.FloatField(
                blank=True,
                help_text=(
                    "Необязательная доля кислорода 0..1 для будущей оценки парциального давления. "
                    "Пустое значение означает, что состав атмосферы канонически неизвестен."
                ),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="atmosphericsnapshot",
            name="format_version",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="atmosphericsnapshot",
            name="solver_version",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="weatherstate",
            name="condition",
            field=models.CharField(
                choices=[
                    ("clear", "Ясно"),
                    ("cloudy", "Облачно"),
                    ("rain", "Дождь"),
                    ("storm", "Шторм"),
                    ("snow", "Снег"),
                    ("fog", "Туман"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="weatherstate",
            name="source",
            field=models.CharField(
                choices=[
                    ("legacy_v2", "Региональная weather-v2"),
                    ("atmospheric_grid_v1", "Глобальная атмосферная сетка v1"),
                    ("atmospheric_grid_v2", "Глобальная атмосферная сетка C3"),
                ],
                default="legacy_v2",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="weatherstate",
            name="precipitation_rate_mm_h",
            field=models.FloatField(
                blank=True,
                help_text="Физическая интенсивность осадков C3, мм водного эквивалента в час.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="weatherstate",
            name="precipitation_amount_mm",
            field=models.FloatField(
                blank=True,
                help_text="Осадки за атмосферный timestep C3, мм водного эквивалента.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="weatherstate",
            name="rain_fraction",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="weatherstate",
            name="snow_fraction",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
