# Generated by Django 5.2.17 on 2026-08-08 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='calendar_epoch_year',
            field=models.IntegerField(default=0, help_text='Год, соответствующий нулевой игровой минуте.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='calendar_hours_per_day',
            field=models.PositiveSmallIntegerField(default=24, help_text='Техническое деление дня на часы; не является правилом канона.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='calendar_minutes_per_hour',
            field=models.PositiveSmallIntegerField(default=60, help_text='Техническое деление часа на игровые минуты.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='red_turn_visibility_threshold',
            field=models.FloatField(default=0.5, help_text='Технический порог видимости Ympha (0–1), после которого Виток считается Красным.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
