# Generated by Django 5.2.17 on 2026-08-08 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_turn_is_168_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='star_motion_direction',
            field=models.SmallIntegerField(choices=[(1, 'К востоку'), (-1, 'К западу')], default=1, help_text='Направление обхода света Звезды по карте.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='star_reference_longitude',
            field=models.FloatField(default=0, help_text='Долгота нулевого меридиана светового цикла Звезды. Начальное значение техническое и настраивается GM.', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='world_circumference_km',
            field=models.FloatField(default=72200, help_text='Полная длина мира по экватору, км.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ympha_motion_direction',
            field=models.SmallIntegerField(choices=[(1, 'К востоку'), (-1, 'К западу')], default=1, help_text='Направление обхода света Ympha по карте.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ympha_peak_longitude_at_epoch',
            field=models.FloatField(default=0, help_text='Долгота максимальной ночной видимости Ympha в нулевую минуту. Начальное значение техническое и настраивается GM.', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
