# Generated by Django 5.2.17 on 2026-08-09 01:49

import campaigns.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_star_motion_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='dark_season_max_red_turns',
            field=models.PositiveSmallIntegerField(default=5, help_text='Максимальное число Красных Витков из 13, при котором локальный сезон называется Тёмным. Между порогами сезон считается Смешанным.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='light_season_min_red_turns',
            field=models.PositiveSmallIntegerField(default=8, help_text='Минимальное число Красных Витков из 13, при котором локальный сезон называется Светлым. Технический порог настраивается GM.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='season_weather_modifiers',
            field=models.JSONField(default=campaigns.models.default_season_weather_modifiers, help_text='Настраиваемые технические поправки влажности и вероятности осадков для summer/autumn/winter/spring; это не неизменный канон.'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('dark_season_max_red_turns__lt', models.F('light_season_min_red_turns'))), name='dark_season_threshold_below_light'),
        ),
    ]
