# Generated by Django 5.2.17 on 2026-08-21 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_fardecosmia_canonical_circumference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_normalized', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('player', 'Игрок'), ('gm', 'Мастер')], default='player', max_length=20)),
                ('created_by_label_snapshot', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('token_prefix', models.CharField(max_length=16, unique=True)),
                ('token_hash', models.CharField(max_length=256)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_failed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by_label_snapshot', models.CharField(blank=True, max_length=240)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by_label_snapshot', models.CharField(blank=True, max_length=240)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_campaign_invitations', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaign_invitations', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_campaign_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['campaign', 'created_at'], name='campaign_invite_time_idx'), models.Index(fields=['expires_at'], name='campaign_invite_expiry_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('role', 'player')), name='campaign_invitation_player_only'), models.CheckConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True), _connector='OR'), name='campaign_invite_not_accepted_and_revoked'), models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), fields=('campaign', 'email_normalized'), name='unique_open_campaign_email_invite')],
            },
        ),
    ]
