# Generated by Django 5.2.17 on 2026-08-22 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaigninvitation'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmembership',
            name='active_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_memberships', to='characters.character'),
        ),
    ]
