# Generated by Django 5.2.17 on 2026-08-23 16:16

from django.db import migrations


def preserve_existing_campaign_gms(apps, schema_editor):
    """Make the former implicit trust of existing GMs explicit.

    Before P5.6 every verified Campaign GM could create another Campaign.  The
    policy migration must not silently lock those established operators out,
    while ordinary PLAYER-only users must not gain the new global permission.
    """

    database = schema_editor.connection.alias
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    User = apps.get_model("accounts", "User")
    CampaignMembership = apps.get_model("campaigns", "CampaignMembership")

    content_type, _created = ContentType.objects.using(database).get_or_create(
        app_label="campaigns",
        model="campaign",
    )
    permission, _created = Permission.objects.using(database).get_or_create(
        content_type=content_type,
        codename="create_campaign_as_gm",
        defaults={"name": "Can create campaigns as a trusted Game Master"},
    )
    gm_user_ids = CampaignMembership.objects.using(database).filter(
        role="gm",
    ).values_list("user_id", flat=True).distinct()
    through_model = User.user_permissions.through
    through_model.objects.using(database).bulk_create(
        [
            through_model(user_id=user_id, permission_id=permission.pk)
            for user_id in gm_user_ids
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_campaignmembership_active_character'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'permissions': [('create_campaign_as_gm', 'Can create campaigns as a trusted Game Master')]},
        ),
        migrations.RunPython(
            preserve_existing_campaign_gms,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
