# Generated by Django 5.2.17 on 2026-08-08 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll20CharacterBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll20_character_id', models.CharField(max_length=100)),
                ('roll20_name', models.CharField(blank=True, max_length=255)),
                ('raw_attributes', models.JSONField(blank=True, default=dict)),
                ('normalized_state', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roll20_binding', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Roll20Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('conflict', 'Conflict'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='roll20.roll20characterbinding')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Roll20Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll20_game_id', models.CharField(blank=True, max_length=100)),
                ('sheet_type', models.CharField(default='dnd5e_2014', max_length=50)),
                ('protocol_version', models.PositiveIntegerField(default=1)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll20_connections', to='campaigns.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='roll20characterbinding',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_bindings', to='roll20.roll20connection'),
        ),
        migrations.CreateModel(
            name='Roll20DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Browser Extension', max_length=100)),
                ('token_prefix', models.CharField(max_length=20, unique=True)),
                ('token_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='roll20.roll20connection')),
            ],
        ),
        migrations.CreateModel(
            name='Roll20SyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('snapshot', 'Snapshot'), ('delta', 'Delta')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='roll20.roll20characterbinding')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='roll20characterbinding',
            constraint=models.UniqueConstraint(fields=('connection', 'roll20_character_id'), name='unique_roll20_character_per_connection'),
        ),
    ]
